components:
  parameters:
    page: 
      in: query
      name: page
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
      description:  The page or group of records to get

    size:
      in: query
      name: size
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
      description: The numbers of items to return per page.